rails-app-shogi/rails/src/config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  get 'kentos/create'
  get 'histories/index'
  get 'sessions/new'
  post 'password_resets/check_email'
  post 'password_resets/check_token'
  patch 'password_resets/update_password'
  get 'kifus/random'
  get 'kifus/get_kifus'
  
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/login_check', to: 'sessions#login_check'
  get '/search', to: 'searchs#search'
  post '/favorites', to:'favorites#create'
  delete '/favorites', to:'favorites#destroy'
  resources :users do
    member do
      get :history
      get :favorite #users_controller内のメソッド
    end
  end
  resources :kifus, only: %i[new create show index destroy]
  resources :kentos, only: %i[create show]
  resources :account_activations, only: %i[create]
  resources :password_resets, only: %i[create]
end

rails-app-shogi/rails/src/app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <%= link_to "将棋のお時間", root_url, {class:"logo"} %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <%= form_with(method: :get, url: search_path, class:"d-flex search_form") do |f| %>
          <%= f.text_field :query, required: true, class: 'form-control' %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
        </li>
        <% if logged_in? %>
          <li class="dropdown collapse navbar-collapse">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-toggle="dropdown">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><%= link_to "Settings", edit_user_path(current_user), {class:"dropdown-item"} %></li>
              <li class="divider dropdown-divider"></li>
              <li>
                <%= link_to "Log out", logout_path, {class:"dropdown-item",method: :delete} %>
              </li>
            </ul>
          </li>>
        <% else %>
          <li><%= link_to "ログイン", login_path, {class:"nav-link dropdown-item"} %></li>
          <li><%= link_to "新規登録", signup_path, {class:"nav-link dropdown-item"} %></li>
        <% end %>
      </ul>
    </nav>

  </div>
</header>

rails-app-shogi/rails/src/app/views/layouts/_side_navigation.html.erb
<div class="list-group list-group-flush">

  <% if logged_in? %>
    <%= link_to "マイページ" ,user_path(current_user) ,class:"list-group-item list-group-item-action list-group-item-secondary" %>
    <%= link_to "お気に入り" ,user_path(current_user)+"/favorite" ,class:"list-group-item list-group-item-action list-group-item-secondary" %>
    <%= link_to "棋譜を追加" ,new_kifu_path ,class:"list-group-item list-group-item-action list-group-item-secondary" %>
    <%= link_to "閲覧履歴" ,user_path(current_user)+"/history" ,class:"list-group-item list-group-item-action list-group-item-secondary" %>
  <% end %>

  <%= tag.div class:"list-group-item list-group-item-action list-group-item-secondary" do %>
    好みの棋譜を探す
    <% tags= %w[相掛かり 矢倉 角換わり 横歩取り 三間飛車 四間飛車 角交換四間飛車 角交換中飛車]%>
    <%= tag.div id:"tags" do %>
      <% tags.each do | tag | %>
        <%= link_to tag ,search_path+"?"+japanese_encode(tag), id:"tag" %>
      <% end %>
    <% end %>
  <% end %>

</div>

rails-app-shogi/rails/src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'hello_vue.js' %>

  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= tag.div class: 'app_wrapper' do %>

      <%= tag.div class: 'side' do %>
        <%= render 'layouts/side_navigation' %>
      <% end %>

      <%= tag.div class: 'container' do %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      <% end %>

    <% end %>
  </body>
</html>