rails-app-shogi/rails/src/config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  get 'kentos/create'
  get 'histories/index'
  get 'sessions/new'
  post 'password_resets/check_email'
  post 'password_resets/check_token'
  patch 'password_resets/update_password'
  get 'kifus/random'
  get 'kifus/get_kifus'
  
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/login_check', to: 'sessions#login_check'
  get '/search', to: 'searchs#search'
  post '/favorites', to:'favorites#create'
  delete '/favorites', to:'favorites#destroy'
  resources :users do
    member do
      get :history
      get :favorite #users_controller内のメソッド
    end
  end
  resources :kifus, only: %i[new create show index destroy]
  resources :kentos, only: %i[create show]
  resources :account_activations, only: %i[create]
  resources :password_resets, only: %i[create]
end

rails-app-shogi/rails/src/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

rails-app-shogi/rails/src/app/views/shared/_error_messages_flash.html.erb
<% unless flash.empty? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <% flash.each do |key,value| %>
        <%= value %>
      <% end %>
    </div>
  </div>
<% end %>

rails-app-shogi/rails/src/app/views/shared/_kifu_tag.html.erb
<% if tags.any? %>
<%= tag.div id:"tags" do %>
  <% tags.each do | tag | %>
    <%= link_to tag.name ,search_path+"?"+japanese_encode(tag.name), id:"tag" %>
  <% end %>
<% end %>
<% end %>

rails-app-shogi/rails/src/app/views/shared/_kifu_url_create.html.erb
<%= tag.div class: "kifu" do %>
  <%= link_to kifu_path(kifu), data: {turbolinks: false} do %>
    <%= tag.p class: "kifuUrl" do %>
      <% if(kifu.title != "") %>
        <%= kifu.title %>
      <% else %>
        先手：
        <%= tag.span kifu.player1, id: win_or_lose(1,kifu) %>
        <%= tag.span "VS", id: "vs" %>
        後手：
        <%= tag.span kifu.player2, id: win_or_lose(2,kifu) %>
      <% end %>
      <%= tag.span timewithzone_to_str(kifu.created_at,format="%Y年%-m月%-d日%-H時%-M分"), id: "created" %>
    <% end %>
  <% end %>
  <% if my_kifu?(kifu) %>
    <%= link_to kifu_path(kifu), method: :delete, 
    data: {confirm: "本当に削除してよろしいですか？"},
    id:"deleteUrl" do %>
      <%= tag.p do %>
        <%= tag.span "delete", id: "delete" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

rails-app-shogi/rails/src/app/views/shared/_kifus_item.html.erb
<% kifus.each do | kifu | %>
  <%= render "shared/kifu_url_create", kifu: kifu %> 
<% end %>

rails-app-shogi/rails/src/app/views/shared/_users_item.html.erb
<% users.each do | user | %>
  <%= tag.div class: "user" do %>
    <%= link_to user_path(user) do %>
      <%= tag.span user.name, id: "user_name" %>
    <% end %>

    <% if !current_user.nil? && current_user.admin? %>
      <%= link_to user_path(user), method: :delete,       
      data: { confirm: "本当に削除してよろしいですか？" } ,id: "deleteUrl" do %>
        <%= tag.span "delete", id: "delete" %>
      <% end %>
    <% end %>

  <% end %>
<% end %>